name: Test Suite
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-cache-v1-${{ hashFiles('yarn.lock') }}
      - run: yarn

      - run: yarn build-libs

      - run: yarn test --no-watch --no-progress --browsers=ChromeHeadlessCI

      - run: sudo apt-get update
      - run: sudo apt-get install google-chrome-stable
      - run: yarn e2e integration --protractorConfig=projects/integration/e2e/protractor-ci.conf.js

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-cache-v1-${{ hashFiles('yarn.lock') }}
      - run: yarn

      - run: yarn build-libs

      - run: yarn eslint
      - run: yarn ts-node scripts/dtslint-all
