name: Test Suite
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-cache-v1-${{ hashFiles('yarn.lock') }}
      - run: yarn

      - run: yarn build --prod micro-dash
      - run: yarn build --prod js-core
      - run: yarn build --prod rxjs-core
      - run: yarn build --prod app-state
      - run: yarn build --prod ng-core
      - run: yarn build --prod ng-app-state
      - run: yarn build --prod ng-dev

      - run: yarn test --watch=false --progress=false --browsers=ChromeHeadlessCI

      - run: yarn lint
      - run: yarn eslint
      - run: yarn dtslint projects/app-state/src/typing-tests
      - run: yarn dtslint projects/js-core/src/typing-tests
      - run: yarn dtslint projects/micro-dash/src/typing-tests
      - run: yarn dtslint projects/ng-core/src/typing-tests
      - run: yarn dtslint projects/ng-dev/src/typing-tests
      - run: yarn dtslint projects/rxjs-core/src/typing-tests
